### ISSUE TITLE
Dresden Surgical Anatomy Dataset

### ISSUE THREAD

**Issue by tvercaut** [luiscarlosgph/list-of-surgical-tool-datasets#11]
Although it doesn't seem to provide surgical tool annotation, the Dresden Surgical Anatomy Dataset is highly relevant in this context. We should thus list it here.

Carstens, M., Rinner, F.M., Bodenstedt, S. et al. The Dresden Surgical Anatomy Dataset for Abdominal Organ Segmentation in Surgical Data Science. Sci Data 10, 3 (2023).
https://doi.org/10.1038/s41597-022-01719-2
https://doi.org/10.7303/syn30368675
https://gitlab.com/nct_tso_public/dsad

**Comment by luiscarlosgph** [comment]
Added.
