### ISSUE TITLE
List Bleeding Segmentation (laparoscopic images with segmented bleeding sources)

### ISSUE THREAD

**Issue by tvercaut** [luiscarlosgph/list-of-surgical-tool-datasets#13]
Rabbani, N., Seve, C., Bourdel, N., & Bartoli, A. (2022, December). Video-based computer-aided laparoscopic bleeding management: a space-time memory neural network with positional encoding and adversarial domain adaptation. In International Conference on Medical Imaging with Deep Learning (pp. 961-974). PMLR.
https://proceedings.mlr.press/v172/rabbani22a.html

Dataset:
http://igt.ip.uca.fr/~ab/code_and_datasets/datasets/bleeding_segmentation_v1p0.zip

**Comment by luiscarlosgph** [comment]
Done.

**Comment by liuyx-1** [comment]
> Rabbani, N., Seve, C., Bourdel, N., & Bartoli, A. (2022, December). Video-based computer-aided laparoscopic bleeding management: a space-time memory neural network with positional encoding and adversarial domain adaptation. In International Conference on Medical Imaging with Deep Learning (pp. 961-974). PMLR. https://proceedings.mlr.press/v172/rabbani22a.html
> 
> Dataset: http://igt.ip.uca.fr/~ab/code_and_datasets/datasets/bleeding_segmentation_v1p0.zip

Hello! Thank you for this job, but the dataset cannot be downloaded from this link. Could you please tell me if there are any other ways to obtain it?
