### ISSUE TITLE
Add link to Adrien Bartoli's dataset webpage

### ISSUE THREAD

**Issue by tvercaut** [luiscarlosgph/list-of-surgical-tool-datasets#14]
The following links
http://igt.ip.uca.fr/~ab/code_and_datasets/index.php
http://igt.ip.uca.fr/~ab/code_and_datasets/datasets/
could be provided as part of the "Repositories holding multiple datasets" section:
https://github.com/luiscarlosgph/list-of-surgical-tool-datasets#repositories-holding-multiple-datasets

**Comment by luiscarlosgph** [comment]
Done.
