### ISSUE TITLE
Dataset link

### ISSUE THREAD

**Issue by nwoyecid** [luiscarlosgph/list-of-surgical-tool-datasets#16]
Correct link to CholecT50: https://github.com/CAMMA-public/cholect50
Statistics are provided on the website.

Associated paper: https://www.sciencedirect.com/science/article/abs/pii/S1361841522000846?via%3Dihub

**Comment by luiscarlosgph** [comment]
Hi Nwoye,


Thank you for reporting the issue and also for putting together the Github repo for your dataset!

Corrected as suggested ;)


Cheers,

Luis.
