### ISSUE TITLE
Give pointers to relevant repositories holding multiple datasets

### ISSUE THREAD

**Issue by tvercaut** [luiscarlosgph/list-of-surgical-tool-datasets#5]
- https://endovis.grand-challenge.org/
- https://opencas.webarchiv.kit.edu/
- http://camma.u-strasbg.fr/datasets
- http://hamlyn.doc.ic.ac.uk/vision/
- https://sites.google.com/site/sznitr/code-and-datasets

This can be an unstructured list at the end for example.

**Comment by luiscarlosgph** [comment]
Added as suggested.
