### ISSUE TITLE
List the "Kvasir-Instrument" Dataset

### ISSUE THREAD

**Issue by tvercaut** [luiscarlosgph/list-of-surgical-tool-datasets#6]
https://datasets.simula.no/kvasir-instrument/

It also makes sense to list the landing page in the [multi-dataset section](https://github.com/luiscarlosgph/list-of-surgical-tool-datasets#repositories-holding-multiple-datasets):
https://datasets.simula.no/index.html

**Comment by luiscarlosgph** [comment]
Added.
